from caddyhackapi.models.comment import Comment
from caddyhackapi.models.final_score import FinalScore
from caddyhackapi.models.golf_course import GolfCourse
from caddyhackapi.models.golfer import Golfer
from caddyhackapi.models.hole_by_hole import HoleByHole
from caddyhackapi.models.individual_hole import IndividualHole
from caddyhackapi.models.like import Like
from caddyhackapi.models.num_of_holes import NumOfHoles
from caddyhackapi.models.post import Post
from caddyhackapi.models.comment_final import CommentFinal
from caddyhackapi.models.comment_table import CommentTable
from caddyhackapi.models.like_final import LikeFinal
from caddyhackapi.models.like_table import LikeTable
