# Generated by Django 4.0.3 on 2022-03-11 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caddyhackapi', '0002_holebyhole_holes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holebyhole',
            name='holes',
        ),
        migrations.AlterField(
            model_name='individualhole',
            name='hole_by_hole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holes_for_hole_by_hole', to='caddyhackapi.holebyhole'),
        ),
    ]
