# Generated by Django 4.0.3 on 2022-03-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddyhackapi', '0003_remove_holebyhole_holes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(),
        ),
    ]
