# Generated by Django 4.0.3 on 2022-03-23 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caddyhackapi', '0005_alter_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddyhackapi.golfer')),
                ('hole_by_hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddyhackapi.holebyhole')),
            ],
        ),
        migrations.CreateModel(
            name='LikeFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddyhackapi.finalscore')),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddyhackapi.golfer')),
            ],
        ),
        migrations.CreateModel(
            name='CommentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddyhackapi.golfer')),
                ('hole_by_hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_table', to='caddyhackapi.holebyhole')),
            ],
        ),
        migrations.CreateModel(
            name='CommentFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('final_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_final', to='caddyhackapi.finalscore')),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddyhackapi.golfer')),
            ],
        ),
    ]
