# Generated by Django 4.0.3 on 2022-03-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddyhackapi', '0006_liketable_likefinal_commenttable_commentfinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalscore',
            name='final_likes',
            field=models.ManyToManyField(related_name='final_likes', through='caddyhackapi.LikeFinal', to='caddyhackapi.golfer'),
        ),
        migrations.AddField(
            model_name='holebyhole',
            name='table_likes',
            field=models.ManyToManyField(related_name='table_likes', through='caddyhackapi.LikeTable', to='caddyhackapi.golfer'),
        ),
    ]
